name: 'Build and push image to ECR'
description: 'Build and push image to ECR'
inputs:
  aws_account:
    description: 'AWS Account to use'
    required: true
  build_args:
    description: 'Build args to pass to docker build'
    required: false
  ga_ssh_key:
    description: 'SSH key to use for composer'
    required: false
  ga_ssh_key_pub:
    description: 'SSH key to use for composer'
    required: false
  composer_oauth:
    description: 'Composer oauth token'
    required: false

runs:
  using: 'composite'
  steps:
      - name: Assume role for AWS Account
        uses: bisnow/github-actions-assume-role-for-environment@main
        with:
          aws_account: ${{ inputs.aws_account }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ input.composer_oauth }}"} }'
        with:
          # ssh_key: ${{ inputs.ga_ssh_key }}
          # ssh_key_pub: ${{ inputs.ga_ssh_key_pub }}
          dev: no
          args: --profile --ignore-platform-reqs --optimize-autoloader
          memory_limit: -1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: ${{ inputs.build_args }}
          tags: '${{ env.REGISTRY }}:${{ env.TAG }},${{ env.REGISTRY }}:${{ env.ENVIRONMENT }}'