name: 'Build and push image to ECR'
description: 'Build and push image to ECR'
inputs:
  aws_account:
    description: 'AWS Account to use'
    required: true
  build_args:
    description: 'Build args to pass to docker build'
    required: false
  composer_oauth:
    description: 'Composer oauth token'
    required: false
  platforms:
    description: 'Platforms to build for'
    required: false
    default: linux/amd64,linux/arm64
  dev_package:
    description: 'Dev package to install'
    required: false
    default: no

runs:
  using: 'composite'
  steps:
      - name: Assume role for AWS Account
        uses: bisnow/github-actions-assume-role-for-environment@main
        with:
          aws_account: ${{ inputs.aws_account }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        env:
          COMPOSER_AUTH: "{\"github-oauth\":{\"github.com\":\"${{ inputs.composer_oauth }}\"}}"
        with:
          dev: ${{ inputs.dev_package }}
          args: --profile --ignore-platform-reqs --optimize-autoloader
          memory_limit: -1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          push: true
          build-args: ${{ inputs.build_args }}
          tags: ${{ env.REGISTRY }}:${{ env.TAG }},${{ env.REGISTRY }}:${{ env.ENVIRONMENT }},${{ env.REGISTRY }}:${{ env.GITHUB_SHA }},${{ env.REGISTRY }}:latest,${{ env.REGISTRY }}:${{ env.GITHUB_RUN_ID }}